### ISSUE TITLE
idk how to install

### ISSUE THREAD

**Issue by Yenpinggggggggggggg** [tariq-nasheed/HyperMania#1]
well, i just don't know how to install this mod to sonic mania plus, can someone pls tell me?

**Comment by fnfkidgamingYT** [comment]
same i also need help installing it

**Comment by KioloSage1441** [comment]
I'm not sure how. I tried using things like Main Memory's Mania Mod Loader and it just didn't work.

**Comment by KioloSage1441** [comment]
I figured it out

**Comment by KioloSage1441** [comment]
Here is a detailed guide on how to install the mod:
Note: You will not have the Mania Plus DLC with this method. To use that you must Decomp the game manually. But this method is far easier so pick your poison.

Step 1: 
Download these files:
https://github.com/Rubberduckycooly/Sonic-Mania-Decompilation
https://github.com/Rubberduckycooly/RSDKv5-Decompilation
Extract both separately.

Step 2: 
In the RSDKv5 decomp folder go to x64 folder and copy either the RSDKv5 or RSDKv5U into a folder of its own. (This Folder will be where most things happen)
Open the mania decomp files and using the decomp you selected, and your OS build type (Probably 64 bit) rename the correct file to game.dll and paste it with you RSDKv5 application. (To understand better just open readme.txt)

Step 3:
Open Sonic Mania primary folder and copy Data.rsdk and move it to your mania decomp folder.
Run the RSDKv5 application and it should run, if not refer back to Step 2 and select a different game.dll file

Step 4:
Create a new folder within your Mania decomp folder titled mods.
Then download the version of the HyperMania mod listed in the releases section.
Extract it into a folder inside your mods folder titled HyperMania.

Step 5:
Go back to your Mania Decomp folder and right click on Settings.ini (Might appear as just Settings) and chose edit.
Under the [Game] section create a new line with this text:
devMenu=1
Then close and save.

Step 6:
Run the decompiled mania and once in the game hit escape.
Open the mods tab and hover over HyperMania and tap enter to activate.
Congrats! You've successfully setup the mod

**Comment by KioloSage1441** [comment]
Nvm

**Comment by KioloSage1441** [comment]
it broke

**Comment by KioloSage1441** [comment]
Issues I found with a Pre-decomped method
the transition to hidden palace doesn't work and just places you back in the act with the ring used
using the debug method with up and super changes the music and sonic speed and the ring drain speed but nothing else.
pressing W as "Hyper Sonic", Super Sonic, or in the special stages crashes the game.
Even if you own mania plus you wont have the dlc

**Comment by KioloSage1441** [comment]
im gonna try some more stuff like a manual decomp

**Comment by KioloSage1441** [comment]
or a different decomp version

**Comment by KioloSage1441** [comment]
Ok so I'm just recording issues here. So, here's all I've tried and issues I've come across:

Attempt 1:
I tried using the steam version of the game along with main memory mania mod loader and the name of the mod wouldn't show up in the loader as well as the mod just not working when selected.

Attempt 2:
RubberDuckyCooly's RSDKv5U decomp of the game. It would run the mod but if a Super Ring was entered the act would reload with the special stage being used while in reality nothing happened.
Also pressing W as Super sonic or during a special stage would crash the game.
Using the alternative transformation method (Debug Active, then super transformation while holding up) would change the music and make super sonic and the ring drain faster but nothing else.

Attempt 3:
RubberDuckyCooly's RSDKv5 decomp of the game. Mod would appear in menu but auto deactive if you attempted to run it.

Currently Attempting:
Manual Decomp of the game
(Wish me luck)

**Comment by Yenpinggggggggggggg** [comment]
but, if i get into the giant ring it wont let me get in, it didnt teleport me to hidden palace what can i do?

**Comment by fnfkidgamingYT** [comment]
when ever i loose the special stage the game crashes and closes

**Comment by fnfkidgamingYT** [comment]
and also i try debug thing to transform and it doesnt work

**Comment by fnfkidgamingYT** [comment]
> and also i try debug thing to transform and it doesnt work

nvm i got the debug transform to work but still need help fixing the issue with the special stage crashing when i loose or win

**Comment by AuraofLucario991** [comment]
the instructions leave me very confused, i have decomp Mania but _how do I make the mod actually work?_

**Comment by tariq-nasheed** [comment]
https://github.com/tariq-nasheed/HyperMania/issues/2#issuecomment-1698221041

**Comment by KioloSage1441** [comment]
I used a already decompiled version of it because I own the game on steam and didn't have the storage for the decomp process and it worked fine. Here's the link to that:
https://archive.org/details/mania-plus-decomp-clean
only discrepancy is that the username is Pirated copy but you can change that by editing it in the settings.ini file.

**Comment by KioloSage1441** [comment]
> I used a already decompiled version of it because I own the game on steam and didn't have the storage for the decomp process and it worked fine. Here's the link to that: https://archive.org/details/mania-plus-decomp-clean only discrepancy is that the username is Pirated copy but you can change that by editing it in the settings.ini file.

I do infact own the game legally tho

**Comment by KioloSage1441** [comment]
Gotcha
Not gonna ask why

**Comment by KioloSage1441** [comment]
Probably cus it is still technically piracy

**Comment by KioloSage1441** [comment]
¯\_ (- . -)_/¯

**Comment by KioloSage1441** [comment]
> hey man please dont do this
Okalie Dokalie

**Comment by KioloSage1441** [comment]
Thats my bad oops

**Comment by Yenpinggggggggggggg** [comment]
> [#2 (comment)](https://github.com/tariq-nasheed/HyperMania/issues/2#issuecomment-1698221041)
thanks!
