### ISSUE TITLE
Mod not working.

### ISSUE THREAD

**Issue by 2009Nathan** [tariq-nasheed/HyperMania#11]
Hello. I have an issue with this mod. I use rsdkv5 with sonic mania plus on mobile. When i try to turn it on, it just will not. It will restart the game and it will turn off again. I really want hyper sonic so pls help thanks.

**Comment by chasio2221** [comment]
hi #12 has the same problem

**Comment by tariq-nasheed** [comment]
Android builds are on the todo list but I haven't got around to them yet, when they're released i'll close this issue
