### ISSUE TITLE
Mod is not working with rsdkv5 decompilation sonic mania plus 

### ISSUE THREAD

**Issue by chasio2221** [tariq-nasheed/HyperMania#12]

**Comment by chasio2221** [comment]
cutting-edge RSDKv5U + Mania (Windows) = false
cutting-edge RSDKv5U + Mania (Linux) = false
legacy RSDKv5U + Mania (Windows) = false
legacy RSDKv5U + Mania (Linux) = false

**Comment by chasio2221** [comment]
[https://github.com/tariq-nasheed/HyperMania/issues/11](url)

**Comment by chasio2221** [comment]
#11

**Comment by chasio2221** [comment]
none of the versions of the mod work with the decomp

**Comment by tariq-nasheed** [comment]
What platform are you using? if you're on Android the reply I left on #11 applies here aswell

**Comment by FunFreddy** [comment]
> What platform are you using? if you're on Android the reply I left on #11 applies here aswell

the problem when trying to build on android is related to [line 79](https://github.com/tariq-nasheed/HyperMania/blob/main/src%2Fhypermania%2FMania%2FGlobal%2FZone.h#L79) (EntityBase entityStorage[16];) in src/hypermania/Mania/Global

**Comment by chasio2221** [comment]
wiiu with sonic mania plus using https://gbatemp.net/threads/sonic-mania-wii-u-custom-installers.620286/ with aroma

**Comment by chasio2221** [comment]
Because the decomp is a bit different from normal sonic mania plus i thank you need to edit some code to be compatible with it

**Comment by chasio2221** [comment]
i want this to work

**Comment by chasio2221** [comment]
i find out that save files have this problem https://github.com/Mefiresu/RSDKv5-Decompilation/issues/12#issuecomment-1375857705 so maybe that may be the problem

**Comment by chasio2221** [comment]
they are almost identical, but rdskv5 seems to add some blank spaces

**Comment by chasio2221** [comment]
hey with the new version i'm still having issues when i go up to a big ring in my pre-existing save of all the chaos emeralds on it
it's not flashing like in the video and when I touch it it just gives me the 50 rings and that's like it I probably did something wrong in the installation but on the loading screen for RSDK for wii u it says it loads it?

**Comment by chasio2221** [comment]
im very sorry to reopen this issue

**Comment by c0des1ayr** [comment]
Seems to work with me. Might try to update my copy of the source to see the issue. Just a question, did you build RSDKv5U on Linux with the switch `RETRO_FORCE_CASE_INSENSITIVITY`?

**Comment by chasio2221** [comment]
No i did not i used the the default android build on the releases tab for the https://github.com/Clownacy/Sonic-Mania-Decompilation-Wii-U build of RSDK

**Comment by tariq-nasheed** [comment]
I'm sorry but Wii U isn't a supported platform at this moment and I don't have any experience with developing for it, i'll look into making a port in the future but for now i'm going to close this issue.
