### ISSUE TITLE
Starting a Mania mode save places you in Encore Angel Island

### ISSUE THREAD

**Issue by vPubneutral** [tariq-nasheed/HyperMania#14]
Starting a Mania mode save places you in Encore Angel Island, without the ability to switch characters, making the stage impossible to beat as Sonic.

[I don't think I'm supposed to be here](https://youtu.be/XN2bp5KBVEo)

[We're stuck](https://youtu.be/jHRHGlJ9YGY)

Also, Green Hill Act 1 is kinda just... gone. It's not even in the dev menu level select...

[Something's missing...](https://youtu.be/w2VKTg5i4JU)

If you pick a character that can get through Angel Island Zone, the Green Hill Intro cutscene plays and then it just instantly switches to Green Hill Act 2.

[I think we missed a level](https://youtu.be/Hq5qcQB6a0Y)

This seems to be a new bug as it does not occur in the SHC build. I can try to narrow down which commit caused the issue when I get home from work tomorrow.

**Comment by vPubneutral** [comment]
Took a while, had some family stuff get in the way, but I narrowed it down to the [most recent commit](https://github.com/tariq-nasheed/HyperMania/commit/3a35fd1db8decf3deefaa561d84e7f01ec744f0d). A manual build from the [commit before](https://github.com/tariq-nasheed/HyperMania/commit/bee5000e8a1f2f22150c187e59cd28cac8cc0c4f) does not have the issue.

**Comment by vPubneutral** [comment]
This actually seems to just be an issue with the release itself, in that it is missing the GameConfig.bin in Data/Game. Moving the GameConfig.bin in the mods main directory into Data/Game seems to fix the issue

**Comment by tariq-nasheed** [comment]
made GameConfig.bin the default so people won't be getting issues like this anymore in the next release
