### ISSUE TITLE
Problem when compiling on android

### ISSUE THREAD

**Issue by FunFreddy** [tariq-nasheed/HyperMania#3]
The method for adding a code mod to the game on android is symlinking it in the jni folder. Symlinking the src folder (third image) is the correct way to do so. But after the building process is done, the apk doesn't generate the libhypermania.so file (second image), which is needed in order to make the mod work, as said in the log.txt file (first image).

![Screenshot_20230903_094127_RS File Manager](https://github.com/tariq-nasheed/HyperMania/assets/139718671/6d123cba-96ab-48af-90b1-af6756067d79)
![Screenshot_20230903_094201_RS File Manager](https://github.com/tariq-nasheed/HyperMania/assets/139718671/93846032-8bf4-4188-ad27-c38f407a409c)
![Screenshot_20230903_094232_GitHub](https://github.com/tariq-nasheed/HyperMania/assets/139718671/6afe9073-88c0-408d-bff7-03450f09adc9)

**Comment by tariq-nasheed** [comment]
fixed(?) with #4
